/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vonchenchen_android_video_demos_codec_CodecWrapper */
#include "decoder.h"
#include "yuv_2_rgb.h"
#include "android_native_window.h"
#include "log.h"

#ifndef _Included_com_vonchenchen_android_video_demos_codec_CodecWrapper
#define _Included_com_vonchenchen_android_video_demos_codec_CodecWrapper
#ifdef __cplusplus
extern "C" {
#endif

//enum AVPixelFormat pixelFormat = AV_PIX_FMT_BGR24;
enum AVPixelFormat pixelFormat = AV_PIX_FMT_RGB565LE;
int native_pix_format = PIXEL_FORMAT_RGB_565;

typedef struct _EnvPackage{
    JNIEnv *env;
    jobject *obj;
    jobject *surface;
} EnvPackage;

/*
 * Class:     com_vonchenchen_android_video_demos_codec_CodecWrapper
 * Method:    get_codec
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_znv_codec_CodecWrapper_getCodec(JNIEnv *env, jobject obj){
    decoder *p = new decoder();
    p->initialize(pixelFormat, 480, 272);
    jlong res = (jlong) p;
    return res;
}

//#define VIDEOWIDTH 1280
//#define VIDEOHEIGHT 300
#define VIDEOWIDTH 480
#define VIDEOHEIGHT 272
int const IMG_FRAME_SIZE = VIDEOWIDTH * VIDEOHEIGHT * 3;

const short RGB565_MASK_RED = (0x1F)<<11;
const short RGB565_MASK_GREEN = (0x3F)<<5;
const short RGB565_MASK_BLUE = (0x1F);

void rgb5652bgr888(short *src, char *dest, int size){
    for(int i = 0; i<  size; i++){
        unsigned short RGB16 = *src;
        dest[i*3+2] = (RGB16&RGB565_MASK_RED) >> 11;
        dest[i*3+1] = (RGB16&RGB565_MASK_GREEN) >> 5;
        dest[i*3+0] = (RGB16&RGB565_MASK_BLUE);
        dest[i*3+2] <<= 3;
        dest[i*3+1] <<= 2;
        dest[i*3+0] <<= 3;
        src++;
    }
}

void save_rgb_image(AVFrame *pFrame){

//    static int flag = 0;
//    flag++;
//    if(flag == 40) {
//        LOGE("save_rgb_image saving ...");
//        flag ++;
//
//        //save rgb565
//        char *dest = (char *)malloc(VIDEOWIDTH * VIDEOHEIGHT * 3);
//        rgb5652bgr888((short *)pFrame->data[0], dest, VIDEOWIDTH * VIDEOHEIGHT);
//        IplImage *iplImagePre = cvCreateImage(cvSize(VIDEOWIDTH, VIDEOHEIGHT), 8, 3);
//        memcpy(iplImagePre->imageData, dest, VIDEOWIDTH * VIDEOHEIGHT * 3);
//        cvSaveImage("/storage/emulated/0/android_video_demo/image.jpeg", iplImagePre);
//
//        //save rgb24
//        /*IplImage *iplImagePre = cvCreateImage(cvSize(VIDEOWIDTH, VIDEOHEIGHT), 8, 3);
//        memcpy(iplImagePre->imageData, pFrame->data[0], IMG_FRAME_SIZE);
//        cvSaveImage("/storage/emulated/0/android_video_demo/image.jpeg", iplImagePre);*/
//
//        LOGE("save_rgb_image saved ...");
//    }
}

void handle_data(AVFrame *pFrame, void *param, void *ctx){

    RenderParam *renderParam = (RenderParam *)param;

    AVFrame	*rgbFrame = yuv420p_2_argb(pFrame, renderParam->swsContext, renderParam->avCodecContext, pixelFormat);//AV_PIX_FMT_RGB565LE

    LOGE("width %d height %d",rgbFrame->width, rgbFrame->height);

    //for test decode image
    //save_rgb_image(rgbFrame);

    EnvPackage *envPackage = (EnvPackage *)ctx;
    ANativeWindow *aNativeWindow = ANativeWindow_fromSurface(envPackage->env, *(envPackage->surface));

    VoutInfo voutInfo;
    voutInfo.buffer = rgbFrame->data[0];
    voutInfo.buffer_width = rgbFrame->width;
    voutInfo.buffer_height = rgbFrame->height;
    voutInfo.pix_format = native_pix_format;

    android_native_window_display(aNativeWindow, &voutInfo);

    ANativeWindow_release(aNativeWindow);

    av_free(rgbFrame->data[0]);
    av_free(rgbFrame);
}

/*
 * Class:     com_vonchenchen_android_video_demos_codec_CodecWrapper
 * Method:    decode_stream
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_znv_codec_CodecWrapper_decodeStream
        (JNIEnv *env, jobject obj, jbyteArray jdata, jint length, jlong this_obj_long, jobject surface){

    decoder *this_obj = (decoder *)this_obj_long;
    jbyte *cdata = env->GetByteArrayElements(jdata, JNI_FALSE);
    jbyte *cdata_rec = cdata;

    if(cdata != NULL) {
        EnvPackage package;
        package.env = env;
        package.obj = &obj;
        package.surface = &surface;

        int len = 0;
        while (1) {
            if (length > INBUF_SIZE) {
                len = INBUF_SIZE;
                length -= INBUF_SIZE;
            } else if (length > 0 && length <= INBUF_SIZE) {
                len = length;
                length = 0;
            } else {
                break;
            }
            //decode h264 cdata to yuv and save yuv data to avFrame which would be passed to handle_data
            this_obj->decodeFrame(cdata, len, handle_data, &package);
            cdata = cdata + len;
            LOGE("decode length: %d ", len);
            //this_obj->decodeFrame(cdata, length, handle_data, NULL);
        }

    }else{
        LOGE("stream data is NULL");
    }
    env->ReleaseByteArrayElements(jdata, cdata_rec, 0);
}

/*
 * Class:     com_vonchenchen_android_video_demos_codec_CodecWrapper
 * Method:    release_codec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_znv_codec_CodecWrapper_releaseCodec(JNIEnv *env, jobject obj, jlong this_obj_long){

    decoder *this_obj = (decoder *)this_obj_long;

    this_obj->close();
    delete this_obj;
}
#ifdef __cplusplus
}
#endif
#endif
