/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_znv_decoder_NativeLib */

#ifndef _Included_com_znv_decoder_NativeLib
#define _Included_com_znv_decoder_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    initDecode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_znv_decoder_NativeLib_initDecode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    initHardDecode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_znv_decoder_NativeLib_initHardDecode
        (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    decodeH264
 * Signature: ([BIJLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_znv_decoder_NativeLib_decodeH264
  (JNIEnv *, jobject, jbyteArray, jint, jlong, jobject);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    hardDecode
 * Signature: ([BIJLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_znv_decoder_NativeLib_hardDecode
        (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    releaseDecode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_znv_decoder_NativeLib_releaseDecode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    releaseHardDecode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_znv_decoder_NativeLib_releaseHardDecode
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_znv_decoder_NativeLib
 * Method:    decodeToYuv
 * Signature: ([BIJ[B)V
 */
JNIEXPORT void JNICALL Java_com_znv_decoder_NativeLib_decodeToYuv
        (JNIEnv *, jobject, jbyteArray, jint, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
